### PR TITLE
Add CI for ayab-esp32

### PR DESCRIPTION
**Pull request by VIPQualityPost**

### CODE REVIEW

**Comment by VIPQualityPost** [comment]
This adds:
- On any PR involving ayab-esp32 directory, it does ERC and DRC checks and makes sure they are clean
- On any PR that gets merged into main, assembly documentation is generated and saved as an artifact from the action. Unclear to me at this point the best way to keep the artifact as these have a limited life of 1 month or something. Possible to self-create another PR with [no ci] flag so that those files can get pushed into repo but I did not try to do that yet.

**Comment by t0mpr1c3** [comment]
If it's a tagged version, you could upload the artifact to the release, otherwise 1 month is probably fine.

**Comment by VIPQualityPost** [comment]
Yea, I was thinking more on it last night, and I think that generating the artifact on each merge to main is good, and then when we actually cut a hardware release (i.e. buy boards) then we can just take the artifact and upload to a release makes sense, at least for all the production files as we should not circulate un-verified files.
The only question is if we want the auto-generated schematics / layout PDFs to live as part of the repo so that you can peruse "current state" of project easily without needing to download software. This could always come in as a follow up PR with [skip ci] tag although that is a bit manual to remember to do that. Or I can add a git action to open that PR immediately actually.

**Comment by VIPQualityPost** [comment]
OK, this should work, we just need to create a secret github token with repo access. It will open a PR from ayab-hardware/documentation into main, skipping CI to add the generated PDFs to ayab-hardware/ayab-esp32/pdf/

**Comment by t0mpr1c3** [comment]
I don't think we need to keep every single file, just those which would be necessary to regenerate what the typical fab house needs.

**Comment by VIPQualityPost** [comment]
Yes, I set it to only add the PDFs. The "real" production files needed to order are still kept as artifacts so they can be used in a tagged release.
@dl1com can you make the secret GITHUB_TOKEN for this?

**Comment by VIPQualityPost** [comment]
OH, I misunderstood, the token is generated as part of the action, so it is already pre-verified. So this should be good to go.

**Review by dl1com — APPROVED** [review]

**Pull request merged**
