### PR TITLE
Forthcoming version changes to Shieldv2

### PR DESCRIPTION
**Pull request by t0mpr1c3**
I have decided to make a small change to future versions of the shield that I manufacture, namely upgrading the SMD electrolytic cap (which can fall off if the PCB is mistreated) to a tantalum equivalent. I have taken the opportunity to introduce some other changes which are mostly cosmetic in nature. The changes are documented in a new file called CHANGES.md.

### CODE REVIEW

**Comment by LeonFedotov** [comment]
hey @t0mpr1c3 did you end up making some boards? i would love to diy an interface but im having trouble using oshparks/jlc pcb gerber interpreters, any advice? maybe you got a blank board your'e willing to share with me? 
Cheers !

**Comment by chris007de** [comment]
@t0mpr1c3 Is this still relevant? I have to admit that I overlooked this PR.
@oskay Any comments on the changes?

**Comment by oskay** [comment]
I don't see any reason not to approve & merge.

**Comment by t0mpr1c3** [comment]
Thanks!

**Comment by LeonFedotov** [comment]
@t0mpr1c3 hey did you also update the footprint on the top grb file for the new cap(cap3)? ive just got the boards and it seems like the footprint is still big, i guess its solderable but the new cap is much smaller... 
what am i missing?

**Comment by t0mpr1c3** [comment]
Hi Leon

As with some of the other footprints on the board, it is larger than the
specified component so that different components with larger footprints can
also be accommodated if needed.

Tom

**Comment by LeonFedotov** [comment]
@t0mpr1c3 airtight! thanks for your reply :)

**Pull request merged**
